/**
 * CivicSphere — My Documents (Information Center)
 * Static definitions for all 22 government documents.
 * Informational only — no upload data, formats, or file sizes.
 */

import type { GovernmentDocument, DocumentCategoryInfo } from './documentTypes';

export const DOCUMENT_CATEGORIES: DocumentCategoryInfo[] = [
  { id: 'identity',    label: 'Identity Documents',           description: 'Proof of identity and citizenship',          iconName: 'IdCard',       color: '#3B82F6', darkColor: '#60A5FA' },
  { id: 'farmer',     label: 'Farmer Documents',              description: 'Farmer registration & certification',        iconName: 'Tractor',      color: '#16A34A', darkColor: '#4ADE80' },
  { id: 'land',       label: 'Land Records',                  description: 'Land ownership & revenue records',           iconName: 'Map',          color: '#D97706', darkColor: '#FCD34D' },
  { id: 'income',     label: 'Income & Financial',            description: 'Income & financial proof documents',         iconName: 'IndianRupee',  color: '#7C3AED', darkColor: '#A78BFA' },
  { id: 'banking',    label: 'Banking Documents',             description: 'Bank account & DBT linkage documents',      iconName: 'Landmark',     color: '#0891B2', darkColor: '#22D3EE' },
  { id: 'agriculture',label: 'Agriculture Certificates',      description: 'Crop, soil & farming certificates',         iconName: 'Wheat',        color: '#65A30D', darkColor: '#A3E635' },
  { id: 'social',     label: 'Social Category Certificates',  description: 'Caste, minority & disability certificates', iconName: 'Users',        color: '#DC2626', darkColor: '#FCA5A5' },
  { id: 'other',      label: 'Other Government Certificates', description: 'Miscellaneous government documents',        iconName: 'FileText',     color: '#6B7280', darkColor: '#9CA3AF' },
];

export const GOVERNMENT_DOCUMENTS: GovernmentDocument[] = [
  /* ────────────── IDENTITY ────────────── */
  {
    id: 'aadhaar',
    name: 'Aadhaar Card',
    category: 'identity',
    iconName: 'IdCard',
    tagline: 'Unique Identification Authority of India (UIDAI)',
    description: 'Aadhaar is a 12-digit unique identification number issued by the Government of India to every resident. It serves as proof of identity and address and is mandatory for virtually all government scheme benefits.',
    whyRequired: 'Government schemes use Aadhaar for Direct Benefit Transfer (DBT) to ensure subsidies reach the correct beneficiary bank account directly. It eliminates duplicate applications and prevents fraud across all welfare programs.',
    howToObtain: [
      'Visit the nearest Aadhaar Enrolment Centre, MeeSeva, or Common Service Centre (CSC)',
      'Carry original proof of identity (passport, voter ID, PAN) and address proof',
      'Get biometrics (fingerprints and iris scan) recorded by the enrolment operator',
      'Collect the Enrolment ID (EID) acknowledgement slip',
      'Download e-Aadhaar from UIDAI portal (uidai.gov.in) in 5–10 working days',
    ],
    issuingAuthority: 'UIDAI — Unique Identification Authority of India',
    issuingOffice: 'UIDAI Enrolment Centre / MeeSeva / Common Service Centre',
    validity: 'Lifetime valid (children must update biometrics at age 5 and 15)',
    importantNotes: [
      'Aadhaar must be linked to your bank account for Direct Benefit Transfer (DBT)',
      'Mobile number should be registered with Aadhaar for OTP-based authentication',
      'Use "Masked Aadhaar" when sharing with third parties for privacy',
      'e-Aadhaar downloaded from UIDAI portal is legally valid',
      'Update Aadhaar address when you change your residence',
    ],
    commonMistakes: [
      'Not linking Aadhaar to bank account — causes all DBT scheme payments to fail',
      'Name mismatch between Aadhaar and bank account — causes scheme rejection',
      'Inactive mobile number — prevents OTP-based e-KYC verification',
      'Using old Aadhaar with outdated address for local scheme applications',
    ],
    requiredInfo: ['12-digit Aadhaar number', 'Full name', 'Date of birth', 'Gender', 'Address', 'QR code'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'PMFBY', 'PM Awas Yojana', 'MGNREGA', 'PM Jan Dhan Yojana', 'Soil Health Card Scheme'],
    isMostRequired: true,
  },
  {
    id: 'pan',
    name: 'PAN Card',
    category: 'identity',
    iconName: 'CreditCard',
    tagline: 'Permanent Account Number — Income Tax Department of India',
    description: 'PAN (Permanent Account Number) is a 10-character alphanumeric identifier issued by the Income Tax Department. It is used for all financial transactions, tax filings, and banking operations across India.',
    whyRequired: 'Required for schemes involving large financial benefits, tax exemptions, agricultural infrastructure loans, and credit-linked programs. Land transactions and crop insurance for large farmers also require PAN linkage.',
    howToObtain: [
      'Apply online at the NSDL portal (tin-nsdl.com) or UTIITSL portal',
      'Fill Form 49A (Indian citizens) with personal details and upload identity, address, and DOB proof',
      'Pay the nominal application fee online (approximately ₹107)',
      'PAN card dispatched to registered address within 15–20 working days',
      'Instant e-PAN also available for Aadhaar holders at incometax.gov.in',
    ],
    issuingAuthority: 'Income Tax Department, Government of India',
    issuingOffice: 'NSDL / UTIITSL / TIN Facilitation Centres / Online Portal',
    validity: 'Lifetime valid',
    importantNotes: [
      'Instant e-PAN is free for Aadhaar holders with registered mobile number',
      'PAN must be linked with Aadhaar — mandatory since 2023',
      'Name on PAN must match exactly with Aadhaar and bank account',
      'PAN is mandatory for all financial transactions above ₹50,000',
    ],
    commonMistakes: [
      'Name spelling differs between PAN and Aadhaar — must match exactly',
      'PAN not linked with Aadhaar — can cause income tax and scheme issues',
      'Not informing bank about PAN for linking with account',
    ],
    requiredInfo: ['10-character PAN number', 'Full name', 'Date of birth', "Father's name", 'Signature'],
    relatedSchemes: ['Agricultural Infrastructure Fund', 'PM Fasal Bima Yojana (large farmers)', 'Kisan Credit Card', 'PMEGP'],
    isMostRequired: false,
  },
  {
    id: 'ration_card',
    name: 'Ration Card',
    category: 'identity',
    iconName: 'BookOpen',
    tagline: 'Public Distribution System — State Civil Supplies Department',
    description: 'A Ration Card is an official document issued by state governments to households for purchasing subsidized food grains through the Public Distribution System (PDS). It also serves as identity and residence proof and establishes a household\'s income category.',
    whyRequired: 'Ration cards establish the household income category (APL/BPL/AAY) that determines eligibility thresholds for agriculture and welfare schemes. BPL ration card holders receive enhanced benefits and higher subsidy percentages.',
    howToObtain: [
      'Visit the village secretariat, gram panchayat, or civil supplies office',
      'Fill the application form with details of all family members and their Aadhaar numbers',
      'Submit income proof, address proof, and existing ration card (if renewing)',
      'New smart ration card issued within 30 days of application',
      'Track status via the state civil supplies portal',
    ],
    issuingAuthority: 'Civil Supplies Department, State Government',
    issuingOffice: 'Village Secretariat / Civil Supplies Office / MeeSeva',
    validity: 'Valid until household income category or composition changes',
    importantNotes: [
      'APL = Above Poverty Line, BPL = Below Poverty Line, AAY = Antyodaya Anna Yojana (poorest of poor)',
      'BPL ration card holders qualify for higher subsidy rates in most schemes',
      'All family members\' Aadhaar numbers must be seeded into the ration card',
      'Smart ration cards have QR codes for biometric authentication at PDS shops',
      'Update ration card when family members are added or removed',
    ],
    commonMistakes: [
      'Income category mismatch — wrong APL/BPL classification',
      'Family members\' Aadhaar not linked to ration card — causes PDS denial',
      'Outdated address not matching current residence',
    ],
    requiredInfo: ['Ration card number', 'Household head name', 'Family member names', 'Category (APL/BPL/AAY)', 'State and district', 'Village details'],
    relatedSchemes: ['PM Garib Kalyan Ann Yojana', 'Antyodaya Anna Yojana', 'National Food Security Act schemes', 'Rythu Bharosa (BPL category)'],
    isMostRequired: false,
  },
  {
    id: 'passport_photo',
    name: 'Passport Size Photograph',
    category: 'identity',
    iconName: 'Camera',
    tagline: 'Recent Coloured Photograph — 3.5 cm × 4.5 cm',
    description: 'A recent passport-size photograph (3.5 cm × 4.5 cm, plain white/light background, front-facing) is a standard requirement for all government scheme applications, ID card issuance, and official registrations.',
    whyRequired: 'Used for identity verification during scheme enrollment, Farmer ID card printing, and physical documentation of scheme applications at government offices and bank branches.',
    howToObtain: [
      'Visit any professional photography studio — specify "passport size for government forms"',
      'White or plain light-coloured background is mandatory',
      'Front-facing, without sunglasses or head covering (except religious)',
      'For digital submissions, photograph must be minimum 600×600 pixels',
      'Online tools can resize and format photographs to passport specifications',
    ],
    issuingAuthority: 'Any Professional Photography Studio',
    issuingOffice: 'Photo Studio / Self-captured Digital Photograph',
    validity: 'Photographs should be taken within 6 months of application',
    importantNotes: [
      'White or light-coloured background is mandatory for all official photographs',
      'Facial features must be clearly visible — no hat, sunglasses, or face covering',
      'Digital photos for online portals should be JPEG format, under 100 KB',
      'Physical application forms typically require 2–4 recent photographs',
    ],
    commonMistakes: [
      'Coloured or patterned backgrounds — rejected by most government portals',
      'Wearing sunglasses or face covering',
      'Photo taken more than 6 months ago — considered outdated',
      'Low resolution photo — blurry when printed on ID cards',
    ],
    requiredInfo: ['Clear front-facing face', 'White or light background', 'No accessories obstructing face'],
    relatedSchemes: ['Farmer ID Registration', 'PM-Kisan KYC', 'MGNREGA Job Card', 'Kisan Credit Card'],
    isMostRequired: false,
  },
  {
    id: 'mobile_verification',
    name: 'Mobile Number (Aadhaar-Linked)',
    category: 'identity',
    iconName: 'Smartphone',
    tagline: 'Registered & Aadhaar-Linked Mobile — UIDAI / TRAI',
    description: 'An active mobile number registered in your name and linked to your Aadhaar is a prerequisite for online government scheme enrollment, OTP-based e-KYC verification, and receiving scheme notifications and payment alerts.',
    whyRequired: 'Government portals (PM-Kisan, PMFBY, Rythu Bharosa) use OTP authentication via the Aadhaar-linked mobile for identity verification. DBT payment confirmations and scheme alerts are sent to this number.',
    howToObtain: [
      'Visit the nearest Aadhaar Enrolment Centre or UIDAI partner centre to link mobile with Aadhaar',
      'Use UIDAI\'s myAadhaar portal or mAadhaar app for online mobile update',
      'Visit your mobile service provider store to ensure the SIM is registered in your name',
      'Verify linkage status at myaadhaar.uidai.gov.in → "Verify Email/Mobile"',
    ],
    issuingAuthority: 'UIDAI (for Aadhaar-mobile linkage)',
    issuingOffice: 'UIDAI Enrolment Centre / myAadhaar Portal / Mobile Store',
    validity: 'Valid while mobile number remains active',
    importantNotes: [
      'Aadhaar-linked mobile is mandatory for e-KYC in PM-Kisan and similar portals',
      'Mobile must be active — recharge regularly to prevent deactivation',
      'Avoid linking a relative\'s mobile — use your own number for scheme alerts',
      'Same number should ideally be registered across PM-Kisan, Rythu Bharosa, and bank accounts',
    ],
    commonMistakes: [
      'Mobile not linked to Aadhaar — OTP fails and e-KYC cannot be completed',
      'Inactive SIM or expired prepaid number — OTP delivery fails',
      'Different numbers registered in different government portals causing confusion',
    ],
    requiredInfo: ['Active mobile number', 'Aadhaar linkage confirmation', 'Name matching mobile SIM registration'],
    relatedSchemes: ['PM-Kisan e-KYC', 'Rythu Bharosa (OTP verification)', 'PMFBY', 'Digital Ration Card e-KYC'],
    isMostRequired: false,
  },

  /* ────────────── INCOME ────────────── */
  {
    id: 'income_certificate',
    name: 'Income Certificate',
    category: 'income',
    iconName: 'IndianRupee',
    tagline: 'Annual Family Income Proof — Revenue Department / Tahsildar',
    description: 'An Income Certificate is an official document issued by the Revenue Department certifying the total annual income of a family or individual. It is the primary proof used by government schemes to determine financial eligibility.',
    whyRequired: 'Most agricultural welfare schemes have income-based eligibility thresholds (e.g., annual income below ₹2 lakh or ₹5 lakh). The income certificate verifies the family qualifies under the scheme\'s income limit.',
    howToObtain: [
      'Apply at the Village Secretariat, MeeSeva centre, or nearest Mandal Revenue Office',
      'Submit Aadhaar card, ration card, and any salary slips or income proof documents',
      'Tahsildar (Revenue Officer) verifies income through official records',
      'Income certificate issued within 7–15 working days',
      'Available as a digital certificate with QR code from MeeSeva for easy verification',
    ],
    issuingAuthority: 'Revenue Department / Tahsildar (Mandal Revenue Officer)',
    issuingOffice: 'Village Secretariat / MeeSeva / Mandal Revenue Office (MRO)',
    validity: '1 year from date of issue — must be renewed annually',
    importantNotes: [
      'Income certificate is valid for only 1 year — obtain fresh certificate for each scheme application season',
      'Family income includes all earning members — not just the applicant',
      'Income should be stated as per the scheme\'s threshold for best results',
      'Digital MeeSeva certificates with QR codes are preferred by most government portals',
      'Declare income accurately — false declaration can lead to scheme cancellation and legal action',
    ],
    commonMistakes: [
      'Using expired certificate (older than 1 year) — causes immediate rejection',
      'Family income stated without including all earning members',
      'Wrong financial year mentioned on the certificate',
    ],
    requiredInfo: ['Applicant full name', 'Annual family income amount', 'Financial year', 'Tahsildar signature and seal', 'Certificate number and date'],
    relatedSchemes: ['Rythu Bharosa', 'PM-Kisan', 'PMFBY', 'PM Awas Yojana Gramin', 'Aam Aadmi Bima Yojana', 'Scholarship Schemes'],
    isMostRequired: true,
  },

  /* ────────────── SOCIAL ────────────── */
  {
    id: 'caste_certificate',
    name: 'Caste Certificate',
    category: 'social',
    iconName: 'Users',
    tagline: 'Social Category Proof — Revenue Department / Tahsildar',
    description: 'A Caste Certificate is an official government document certifying a person\'s caste or community (SC, ST, OBC, EWS, etc.) as defined under the Constitution of India. It enables access to reservations, higher subsidies, and targeted welfare schemes.',
    whyRequired: 'Several agriculture schemes offer higher subsidy percentages, relaxed income limits, or priority allocation to SC/ST/OBC farmers. Caste certificates prove eligibility for these category-specific scheme components.',
    howToObtain: [
      'Apply at the Village Secretariat, MeeSeva, or Mandal Revenue Office',
      'Submit Aadhaar card, ration card, and community proof (parent\'s caste certificate or community leader declaration)',
      'Tahsildar verifies community status through official records',
      'Certificate issued in 7–15 working days; digital MeeSeva certificate available',
    ],
    issuingAuthority: 'Revenue Department / Tahsildar',
    issuingOffice: 'Village Secretariat / MeeSeva / Mandal Revenue Office',
    validity: 'Lifetime valid once issued (for adults)',
    importantNotes: [
      'Different from OBC certificate — ensure you apply for the correct category',
      'Caste name must match official government list (Central/State list)',
      'Digital caste certificate with QR code from MeeSeva is preferred for online applications',
      'May be required to prove eligibility for children\'s scholarships as well',
    ],
    commonMistakes: [
      'Submitting sub-caste certificate instead of the main caste/community certificate',
      'Illegible government seal or signature on physical certificate',
      'Old format certificates not accepted by newer digital portals',
    ],
    requiredInfo: ['Full name', 'Caste/community name', 'Certificate number', 'Issuing Tahsildar name', 'District and state', 'Date of issue'],
    relatedSchemes: ['SC/ST Sub-Plan Agriculture Schemes', 'Post-Matric Scholarships', 'DR BR Ambedkar Welfare Schemes', 'State OBC Welfare Schemes'],
    isMostRequired: false,
  },
  {
    id: 'disability_certificate',
    name: 'Disability Certificate (UDID)',
    category: 'social',
    iconName: 'HeartHandshake',
    tagline: 'Persons with Disabilities — Medical Board / SADAREM',
    description: 'A Disability Certificate (now consolidated under the Unique Disability ID — UDID) certifies the type and percentage of disability after medical board examination. It is required to access government schemes specifically targeting Persons with Disabilities (PwD).',
    whyRequired: 'PwD farmers receive enhanced benefits under several schemes, including higher subsidy percentages, priority allocation, relaxed income criteria, and special category reservations. Minimum 40% disability is required for most scheme benefits.',
    howToObtain: [
      'Visit a government hospital or designated district medical board',
      'Medical examination conducted by specialist doctors determines type and percentage',
      'Apply for UDID card at swavlambancard.gov.in with the disability certificate',
      'UDID card (Unique Disability ID) is now the standard proof for all scheme applications',
      'Also available through SADAREM portal (State-level) for AP/Telangana residents',
    ],
    issuingAuthority: 'Medical Board / SADAREM / Chief Medical Officer',
    issuingOffice: 'Government Hospital / District Medical Officer / SADAREM Portal / swavlambancard.gov.in',
    validity: 'Permanent for permanent disabilities; 5 years for progressive or temporary conditions',
    importantNotes: [
      'UDID card (Unique Disability ID) is now mandatory — physical disability certificate alone may not suffice',
      'Minimum 40% disability is required to qualify for most PwD-specific scheme benefits',
      'Type of disability must be from the 21 recognized categories under RPWD Act 2016',
      'UDID card carries QR code for instant verification at government counters',
    ],
    commonMistakes: [
      'Having disability certificate without obtaining the UDID card — UDID is now mandatory',
      'Disability percentage below 40% — most scheme benefits require 40% or above',
      'Expired temporary certificate — must be renewed as per specified period',
    ],
    requiredInfo: ['UDID card number or Disability certificate number', 'Type of disability', 'Percentage of disability', 'Permanent or temporary', 'Medical board seal and signatures'],
    relatedSchemes: ['Divyangjan Scholarship', 'Agriculture Equipment Subsidy for PwD', 'PM Awas Yojana (PwD category)', 'PMEGP (PwD)', 'NHFDC Schemes'],
    isMostRequired: false,
  },
  {
    id: 'minority_certificate',
    name: 'Minority Certificate',
    category: 'social',
    iconName: 'Shield',
    tagline: 'Religious Minority Status — Minority Welfare Department',
    description: 'A Minority Certificate certifies that a person belongs to a notified religious minority community (Muslim, Christian, Sikh, Buddhist, Jain, or Parsi) as defined under the National Commission for Minorities Act. It enables access to minority welfare programs.',
    whyRequired: 'Minority farmers and citizens receive targeted benefits under Ministry of Minority Affairs schemes and state-level minority welfare programs, including educational support, agricultural assistance, and economic empowerment schemes.',
    howToObtain: [
      'Apply at Village Secretariat, MeeSeva, or District Minority Welfare Office',
      'Submit Aadhaar, ration card showing religion, and community proof',
      'Revenue officer verifies community status and issues certificate',
      'Digital certificate available from MeeSeva with QR code',
    ],
    issuingAuthority: 'Revenue Department / Minority Welfare Department',
    issuingOffice: 'Village Secretariat / MeeSeva / District Minority Welfare Office',
    validity: 'Lifetime valid',
    importantNotes: [
      'Only 6 notified communities qualify: Muslim, Christian, Sikh, Buddhist, Jain, Parsi',
      'State government may have additional notified minority communities',
      'Certificate must show specific religious community name',
      'Do not confuse with OBC certificate — different eligibility criteria',
    ],
    commonMistakes: [
      'Wrong community classification — not among the 6 notified minorities',
      'Missing government seal or issuing authority signature',
      'Confusing minority certificate with OBC/SC/ST certificate',
    ],
    requiredInfo: ['Full name', 'Religion/community name', 'Certificate number', 'Issuing authority seal and signature', 'Date of issue'],
    relatedSchemes: ['National Minorities Development Finance Corporation Schemes', 'Seekho Aur Kamao', 'PM Jan Vikas Karyakram', 'Nai Udaan Scheme'],
    isMostRequired: false,
  },

  /* ────────────── FARMER ────────────── */
  {
    id: 'farmer_id',
    name: 'Farmer ID Card',
    category: 'farmer',
    iconName: 'Tractor',
    tagline: 'Unique Farmer Registration — State Agriculture Department',
    description: 'The Farmer ID Card (also called Kisan ID or Farmer Registration Certificate) is a unique identifier issued to farmers after official registration with the State Agriculture Department. It is the gateway to most modern agriculture scheme benefits.',
    whyRequired: 'The Agriculture Department uses the Farmer ID to validate that the applicant is a genuine registered farmer. It links land records, crop details, PM-Kisan registration, soil health card, and crop insurance data under a single farmer profile.',
    howToObtain: [
      'Visit the local Agriculture Extension Officer (AEO) or Agriculture Department office',
      'Submit Pattadar Passbook (or land record), Aadhaar card, and recent photograph',
      'Fill the farmer registration form with land survey numbers and crop details',
      'Farmer ID generated and card printed within 15 working days',
      'Also register through state agriculture portals (e.g., eFarmer.ap.gov.in for AP)',
    ],
    issuingAuthority: 'State Agriculture Department',
    issuingOffice: 'Agriculture Extension Office / MeeSeva / eFarmer Portal',
    validity: 'Annual renewal recommended (update crop details each season)',
    importantNotes: [
      'Link Aadhaar with Farmer ID for Direct Benefit Transfer across all agriculture schemes',
      'Update crop details every season (Kharif/Rabi) to maintain scheme eligibility',
      'Land details on Farmer ID must match Pattadar Passbook survey numbers',
      'Farmer ID links all scheme benefits — PM-Kisan, Rythu Bharosa, PMFBY — to one profile',
    ],
    commonMistakes: [
      'Outdated land or crop details — causes scheme mismatch',
      'Farmer ID not Aadhaar-linked — DBT payments fail',
      'Missing seasonal crop update — PMFBY insurance cannot be raised',
    ],
    requiredInfo: ['Farmer ID number', 'Farmer name', 'Land survey number(s)', 'Crop type', 'Season registered', 'Aadhaar linkage status'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'PMFBY', 'Soil Health Card Scheme', 'Agriculture Input Subsidy', 'Kisan Credit Card'],
    isMostRequired: true,
  },
  {
    id: 'tenant_farmer_cert',
    name: 'Tenant Farmer Certificate',
    category: 'farmer',
    iconName: 'FileUser',
    tagline: 'Lease Agreement / Licensed Cultivator — Revenue Department',
    description: 'A Tenant Farmer Certificate (or Lease Agreement) is an official document certifying that a farmer cultivates land as a tenant or lessee without owning it. It enables tenant farmers — who form a significant portion of India\'s agricultural community — to access government scheme benefits.',
    whyRequired: 'Historically, tenant farmers were excluded from scheme benefits since they lacked land ownership proof. Several states (including AP under the AP Licensed Cultivators Act) now extend PM-Kisan and other benefits to tenant farmers holding this certificate.',
    howToObtain: [
      'Register the lease/rental agreement at the Village Secretariat or MeeSeva',
      'A notarized lease agreement with the land owner is also accepted',
      'Apply for "Licensed Cultivator" status at the Agriculture Department (Andhra Pradesh specific)',
      'Submit the land owner\'s records and the lease agreement along with Aadhaar',
    ],
    issuingAuthority: 'Revenue Department / Agriculture Department',
    issuingOffice: 'Village Secretariat / Mandal Revenue Office / MeeSeva',
    validity: 'Valid for the duration of the lease agreement (typically 1–3 years)',
    importantNotes: [
      'AP Licensed Cultivator Act specifically protects tenant farmers and enables scheme access',
      'Lease agreement must be signed by both tenant and land owner',
      'Registered agreements are more legally sound than notarized ones',
      'Tenant farmers are now included in PM-Kisan — check state-specific guidelines',
    ],
    commonMistakes: [
      'Unregistered or unnotarized lease agreement — not accepted as official proof',
      'Missing land owner signature on agreement',
      'Agreement period expired before scheme application',
    ],
    requiredInfo: ['Tenant farmer name', 'Land owner name', 'Survey number of leased land', 'Lease period', 'Crop to be cultivated', 'Both parties\' signatures'],
    relatedSchemes: ['PM-Kisan (Tenant Category)', 'AP Rythu Bharosa (Tenant Category)', 'PMFBY for Tenant Farmers', 'Licensed Cultivators Scheme (AP)'],
    isMostRequired: false,
  },
  {
    id: 'livestock_certificate',
    name: 'Livestock Ownership Certificate',
    category: 'farmer',
    iconName: 'PawPrint',
    tagline: 'Animal Husbandry Department — Veterinary Assistant Surgeon',
    description: 'A Livestock Ownership Certificate is an official document from the Animal Husbandry Department certifying the types and number of livestock (cattle, buffalo, goats, sheep, poultry) owned by a farmer. Required for livestock and dairy-related government schemes.',
    whyRequired: 'Schemes such as PM Livestock Insurance (PMSBY), NABARD dairy development loans, and state livestock subsidy programs require proof of livestock ownership to extend benefits. It also qualifies farmers for allied agriculture support schemes.',
    howToObtain: [
      'Visit the local Veterinary Dispensary or Animal Husbandry Extension Office',
      'Provide Aadhaar and details of all animals owned (species, age, approximate value)',
      'Veterinary Assistant Surgeon (VAS) conducts physical verification and issues certificate',
      'Animals may need to be officially tagged/ear-tagged for registration',
    ],
    issuingAuthority: 'Animal Husbandry Department / Veterinary Surgeon',
    issuingOffice: 'Veterinary Dispensary / Animal Husbandry Extension Office',
    validity: '1 year (updated with livestock census or when animals are sold/born)',
    importantNotes: [
      'Tag or ear-mark all animals for official registration',
      'Update certificate when animals are sold, die, or new animals are born',
      'Dairy schemes require milch cattle specifically — list milch and draught separately',
      'For poultry schemes, flock size and breed type must be specified',
    ],
    commonMistakes: [
      'Missing animal count update when animals are sold or new ones added',
      'Unregistered/untagged animals — VAS cannot certify unverified livestock',
      'Outdated certificate from previous year without renewal',
    ],
    requiredInfo: ['Farmer name', 'Type and number of animals', 'Location of farm', 'VAS signature and seal', 'Registration numbers if tagged'],
    relatedSchemes: ['PM Livestock Insurance Scheme', 'Dairy Entrepreneurship Development Scheme', 'NABARD Livestock Loan', 'Goat Farming Subsidy', 'Poultry Development Scheme'],
    isMostRequired: false,
  },

  /* ────────────── LAND ────────────── */
  {
    id: 'pattadar_passbook',
    name: 'Pattadar Passbook',
    category: 'land',
    iconName: 'BookMarked',
    tagline: 'Land Ownership Record — Revenue Department (Andhra Pradesh / Telangana)',
    description: 'Pattadar Passbook is an official government document issued in Andhra Pradesh and Telangana that records land ownership details including survey numbers, extent of land, classification, and any liabilities. It is the primary land ownership proof for farmers in these states.',
    whyRequired: 'Agriculture schemes require land ownership proof to determine farmer eligibility based on land holding size. PM-Kisan, Rythu Bharosa, and crop insurance all use the Pattadar Passbook to verify the farmer owns or has rights over the agricultural land claimed.',
    howToObtain: [
      'Apply at the Village Revenue Office (VRO), MeeSeva, or nearest Mandal Revenue Office',
      'Submit Aadhaar, existing land documents, and survey details',
      'Revenue Inspector verifies land ownership through Dharani portal (AP) or equivalent',
      'Pattadar Passbook printed and issued at VRO level within 15–30 days',
      'Digital version available on Meebhoomi portal (meebhoomi.ap.gov.in)',
    ],
    issuingAuthority: 'Revenue Department, Government of Andhra Pradesh / Telangana',
    issuingOffice: 'Village Revenue Office / Mandal Revenue Office / MeeSeva / Meebhoomi Portal',
    validity: 'Valid until land ownership changes (update on transfer, partition, or inheritance)',
    importantNotes: [
      'Always download the latest copy from Meebhoomi portal for most current ownership records',
      'Ensure survey numbers on Pattadar Passbook match 1B Adangal and ROR records',
      'Upload/submit both the ownership page and the map/survey page when required',
      'Dharani portal (AP) is the authoritative digital land record system',
      'Any land disputes must be resolved before applying for scheme benefits',
    ],
    commonMistakes: [
      'Using old passbook with incorrect or outdated ownership details',
      'Survey number page missing or unclear when submitting for schemes',
      'Illegible handwritten entries on older physical passbooks',
    ],
    requiredInfo: ['Survey number(s)', 'Extent of land (in acres/cents)', 'Land type classification', 'Owner name', 'Village and mandal', 'Any liabilities or encumbrances'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'PMFBY', 'Agricultural Land Development', 'Irrigation Subsidy Schemes', 'Soil Health Card'],
    isMostRequired: true,
  },
  {
    id: 'land_ownership_record',
    name: 'Land Ownership Record (ROR / 1-A)',
    category: 'land',
    iconName: 'Map',
    tagline: 'Record of Rights — Dharani / Meebhoomi Portal',
    description: 'The Land Ownership Record (Record of Rights — ROR, also called 1-A) is a digital land record maintained by the Revenue Department showing ownership, cultivation status, liabilities, and survey details for agricultural land. It is the modern digital equivalent of physical land records.',
    whyRequired: 'Required for land-based schemes to verify the area, ownership, and current cultivation status of the land for which scheme benefits are sought. Schemes like PM-Kisan verify that the applicant owns cultivable agricultural land.',
    howToObtain: [
      'Download directly from Meebhoomi portal (meebhoomi.ap.gov.in) — search by survey number or owner name',
      'Available at VRO office and MeeSeva centres as certified copies',
      'For Telangana: use Dharani portal (dharani.telangana.gov.in)',
      'For other states: visit local Revenue Department or use state-specific land record portal',
    ],
    issuingAuthority: 'Revenue Department via Meebhoomi / Dharani / State Land Record Portal',
    issuingOffice: 'Online Portal (Meebhoomi / Dharani) / MeeSeva / VRO Office',
    validity: 'Updated each season with crop entries — always use current season records',
    importantNotes: [
      'Always use the most recent season\'s ROR as schemes verify current cultivation',
      'Land extents on ROR must match Pattadar Passbook — any discrepancy must be corrected',
      'Crop column entries confirm what crop is currently grown — critical for PMFBY',
      'ROR is the primary land record for all online scheme portals',
    ],
    commonMistakes: [
      'Using outdated season ROR — scheme portals verify current season records',
      'Crop column empty when crop is registered — causes PMFBY claim issues',
      'Land area discrepancy between ROR and Pattadar Passbook — must be reconciled',
    ],
    requiredInfo: ['Survey number', 'Owner name', 'Extent of land', 'Type of land', 'Current crop details', 'Encumbrances if any'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'PMFBY Crop Insurance', 'Irrigation Subsidy', 'Soil Health Card Scheme'],
    isMostRequired: true,
  },
  {
    id: 'adangal_1b',
    name: '1B Adangal (Pahani)',
    category: 'land',
    iconName: 'ScrollText',
    tagline: 'Crop Cultivation Record — Village Revenue Officer (Andhra Pradesh)',
    description: '1B Adangal (also called Pahani) is an official land and cultivation record maintained by the Village Revenue Officer (VRO) in Andhra Pradesh. It contains seasonal crop cultivation details, land type, ownership, and water source information for each survey number.',
    whyRequired: 'Crop insurance (PMFBY), Soil Health Card, and agricultural input subsidies require the 1B Adangal to verify what crop has been grown in the current season, the area under cultivation, and the irrigation source used.',
    howToObtain: [
      'Download from Meebhoomi portal (meebhoomi.ap.gov.in) → Adangal section',
      'Enter district, mandal, village, and survey number to view and download Adangal',
      'Available as certified copy at VRO office and MeeSeva centres',
      'Always download for the current season (Kharif: June–October; Rabi: October–March)',
    ],
    issuingAuthority: 'Village Revenue Officer (VRO), Revenue Department, Andhra Pradesh',
    issuingOffice: 'Meebhoomi Portal (Online) / MeeSeva / VRO Office',
    validity: 'Season-specific — updated each Kharif and Rabi season',
    importantNotes: [
      'Always download the Adangal for the current crop season before applying for PMFBY or input subsidy',
      'Crop type must match what is declared in the scheme application',
      'Survey number and land extent must match Pattadar Passbook',
      'If crop is not updated in Adangal, approach VRO to enter current season crop details',
    ],
    commonMistakes: [
      'Uploading previous season Adangal when current season is required',
      'Crop column blank or incorrect crop type — causes PMFBY claim rejection',
      'Missing village and survey number details',
    ],
    requiredInfo: ['Survey number', 'Khathadar (owner/cultivator) name', 'Extent of land', 'Crop details for current season', 'Season (Kharif/Rabi)', 'VRO seal'],
    relatedSchemes: ['PMFBY', 'Agriculture Input Subsidy', 'Crop Compensation Scheme', 'Soil Health Card'],
    isMostRequired: false,
  },

  /* ────────────── BANKING ────────────── */
  {
    id: 'bank_passbook',
    name: 'Bank Passbook (First Page)',
    category: 'banking',
    iconName: 'Landmark',
    tagline: 'DBT-Linked Bank Account — Nationalized or Cooperative Bank',
    description: 'The first page of a Bank Passbook shows the account holder\'s name, account number, IFSC code, and bank branch details. It is the primary document used to verify the bank account for Direct Benefit Transfer (DBT) of government scheme payments.',
    whyRequired: 'All government scheme benefits (PM-Kisan, Rythu Bharosa, PMFBY, MGNREGA) are transferred directly to the farmer\'s bank account via DBT. The bank passbook verifies the account exists, is active, and the name matches Aadhaar for seeding.',
    howToObtain: [
      'Passbook is provided when opening a bank account — ensure first page is updated',
      'Visit bank branch for passbook update and to confirm account is active',
      'Link Aadhaar to your bank account at the bank branch or via internet/mobile banking',
      'Verify NPCI (National Payments Corporation of India) Aadhaar seeding at your bank',
    ],
    issuingAuthority: 'Nationalized Bank / Cooperative Bank / Regional Rural Bank (RRB)',
    issuingOffice: 'Bank Branch (SBI, Canara Bank, Andhra Bank, Indian Bank, etc.)',
    validity: 'Valid as long as the bank account is active',
    importantNotes: [
      'Bank account must be Aadhaar-seeded (NPCI mapped) for DBT — verify this at bank',
      'Account holder name must match Aadhaar name exactly (spelling matters)',
      'Account must be in a nationalized, cooperative, or RRB bank (Aadhaar-linked payment capable)',
      'IFSC code must be visible on the passbook first page',
      'Do not use dormant accounts — accounts inactive for 1+ year may require reactivation',
    ],
    commonMistakes: [
      'Account not Aadhaar-seeded (NPCI not mapped) — all DBT payments fail',
      'Account holder name mismatch with Aadhaar — DBT rejected by bank',
      'Using dormant/closed account for scheme registration',
      'Joint account where primary holder is not the farmer — may cause DBT issues',
    ],
    requiredInfo: ['Account holder name', 'Account number', 'IFSC code', 'Bank name and branch', 'Aadhaar linkage status'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'PMFBY', 'MGNREGA', 'All DBT-linked schemes'],
    isMostRequired: true,
  },

  /* ────────────── AGRICULTURE ────────────── */
  {
    id: 'soil_health_card',
    name: 'Soil Health Card',
    category: 'agriculture',
    iconName: 'Leaf',
    tagline: 'Soil Nutrient Analysis Report — Agriculture Department / Soil Testing Lab',
    description: 'A Soil Health Card (SHC) is an official document issued after soil testing that shows the nutrient status of a farmer\'s land. It includes nutrient levels (NPK, micro-nutrients) and tailored fertilizer and amendment recommendations for improved crop production.',
    whyRequired: 'The Soil Health Card Scheme (SHCS) requires farmers to have a valid SHC to receive scheme subsidies on fertilizers and soil amendments. Multiple schemes reward farmers with valid SHCs through additional benefits and relaxed criteria.',
    howToObtain: [
      'Contact the local Agriculture Extension Officer (AEO) to request soil sample collection',
      'Collect soil samples yourself from multiple spots in the field (if self-collecting)',
      'Submit samples at the nearest Soil Testing Laboratory (STL) with land details',
      'Soil Health Card generated within 30 days after analysis',
      'Download digital SHC from soilhealth.dac.gov.in using Farmer ID or Aadhaar',
    ],
    issuingAuthority: 'Agriculture Department / State Soil Testing Laboratory (STL)',
    issuingOffice: 'Agriculture Extension Office / Soil Testing Laboratory / soilhealth.dac.gov.in',
    validity: '3 years (re-testing required every 3 years)',
    importantNotes: [
      'Collect soil samples from at least 5–8 spots across the field for accurate results',
      'Note the SHC card number — required for linking with farmer profile and schemes',
      'Follow the nutrient recommendations on the card for better yields and scheme eligibility',
      'SHC must be linked with Farmer ID for Soil Health Card Scheme benefits',
      'SHC is free of charge for all registered farmers',
    ],
    commonMistakes: [
      'Using expired card (older than 3 years) — must retest soil',
      'Farmer ID not linked to SHC — scheme system cannot verify farmer eligibility',
      'Different survey number on SHC vs land records — must match exactly',
    ],
    requiredInfo: ['SHC card number', 'Farmer name', 'Survey number', 'Village and mandal', 'Nutrient levels section', 'Recommendations section'],
    relatedSchemes: ['Soil Health Card Scheme (SHCS)', 'PMKSY', 'Organic Farming Mission', 'National Food Security Mission', 'Fertilizer Subsidy Scheme'],
    isMostRequired: false,
  },
  {
    id: 'pm_kisan_proof',
    name: 'PM-Kisan Registration Proof',
    category: 'agriculture',
    iconName: 'FileCheck',
    tagline: 'PM-Kisan Beneficiary Confirmation — Ministry of Agriculture & Farmers Welfare',
    description: 'PM-Kisan Registration Proof confirms that the farmer is a registered beneficiary under the Pradhan Mantri Kisan Samman Nidhi (PM-Kisan) scheme, showing the farmer\'s unique PM-Kisan ID and current installment status.',
    whyRequired: 'Several complementary schemes (Rythu Bharosa state supplement, crop insurance priority, Kisan Credit Card facilitation) require PM-Kisan beneficiary status as a prerequisite. This proof confirms the farmer has been DBT-verified by the central government.',
    howToObtain: [
      'Visit PM-Kisan portal (pmkisan.gov.in) → "Know Your Status" section',
      'Enter Aadhaar number, mobile number, or account number to check status',
      'Download beneficiary status PDF as registration proof',
      'Collect acknowledgment from the Agriculture Extension Office during scheme enrollment',
    ],
    issuingAuthority: 'Ministry of Agriculture & Farmers Welfare, Government of India',
    issuingOffice: 'PM-Kisan Portal (pmkisan.gov.in) / Agriculture Extension Office',
    validity: 'Current for each installment period (4-monthly cycles)',
    importantNotes: [
      'PM-Kisan e-KYC is now mandatory — complete at pmkisan.gov.in or nearest CSC',
      'Aadhaar must be linked to bank account for PM-Kisan installments to be credited',
      'Check "PM-Kisan Status" each installment period to ensure payments are not on hold',
      'Farmer status showing "On Hold" means there is a mismatch that must be corrected',
    ],
    commonMistakes: [
      'Status shows "Rejected" — check Aadhaar-bank linkage and Farmer ID details',
      'e-KYC not completed — PM-Kisan installments blocked since 2023',
      'Bank account number or IFSC mismatch in PM-Kisan portal',
    ],
    requiredInfo: ['PM-Kisan beneficiary ID', 'Farmer name', 'Aadhaar number', 'Bank account details', 'Installment payment status', 'e-KYC status'],
    relatedSchemes: ['PM-Kisan', 'Rythu Bharosa', 'Kisan Credit Card', 'PMFBY (priority enrollment)'],
    isMostRequired: true,
  },
  {
    id: 'organic_farming_cert',
    name: 'Organic Farming Certificate',
    category: 'agriculture',
    iconName: 'Leaf',
    tagline: 'Organic Certification — APEDA / PGS-India',
    description: 'An Organic Farming Certificate is issued by an APEDA-approved third-party certification body (or PGS-India cluster) confirming that the farmer practices organic farming without synthetic chemicals, pesticides, or fertilizers.',
    whyRequired: 'The Paramparagat Krishi Vikas Yojana (PKVY) and other organic farming schemes require this certificate to disburse cluster formation subsidies, input assistance, market linkage support, and certification cost reimbursement.',
    howToObtain: [
      'Join a farmer cluster under PKVY scheme (minimum 50 farmers for group certification)',
      'Apply to an APEDA-approved certification body or PGS-India regional council',
      'For conventional farms: 3-year conversion period is required before certification',
      'PGS-India (Participatory Guarantee System) certification is faster and cheaper for small farmers',
      'Annual farm inspection and renewal required for both NPOP and PGS certification',
    ],
    issuingAuthority: 'APEDA-Approved Certification Body / PGS-India Regional Council',
    issuingOffice: 'APEDA Office / State Organic Farming Board / Agriculture Department',
    validity: '1 year (annual renewal with farm inspection and documentation)',
    importantNotes: [
      'PGS-India certification is more accessible and affordable for small/marginal farmers',
      'Maintain an organic farm diary — required for annual audit',
      'Cluster formation of 50+ farmers qualifies for group certification subsidy under PKVY',
      'Conventional farms need 3 years of organic practice before certification is issued',
    ],
    commonMistakes: [
      'Expired certificate — renewal required annually before applying for scheme benefits',
      'Non-APEDA-approved certifier used — certificate not accepted for central scheme benefits',
      'Missing farm boundary details or crop records in certification documentation',
    ],
    requiredInfo: ['Farmer/cluster name', 'Survey number(s)', 'Certified area', 'Certifying body name', 'Certificate number', 'Certificate validity period'],
    relatedSchemes: ['PKVY — Paramparagat Krishi Vikas Yojana', 'National Project on Organic Farming', 'Mission for Integrated Development of Horticulture', 'State Organic Farming Schemes'],
    isMostRequired: false,
  },
  {
    id: 'crop_insurance_cert',
    name: 'Crop Insurance Certificate (PMFBY)',
    category: 'agriculture',
    iconName: 'Shield',
    tagline: 'Pradhan Mantri Fasal Bima Yojana — Empanelled Insurance Company',
    description: 'The Crop Insurance Certificate is proof of enrollment under Pradhan Mantri Fasal Bima Yojana (PMFBY) or Restructured Weather Based Crop Insurance Scheme (RWBCIS) confirming the farmer\'s crop is insured for the current season against natural calamities.',
    whyRequired: 'Crop insurance is mandatory for credit-linked farmers (KCC holders). It protects farmers against crop loss due to drought, floods, pests, and other natural causes. Certain input subsidy schemes also require PMFBY enrollment as a prerequisite.',
    howToObtain: [
      'KCC (Kisan Credit Card) holders are automatically enrolled — verify with your bank',
      'Apply online on PMFBY portal (pmfby.gov.in) with Farmer ID and land documents',
      'Apply through Common Service Centres (CSCs) or Agriculture Extension Office',
      'Submit land records, crop details, and pay the applicable premium',
      'Insurance policy issued by the empaneled insurance company for your district',
    ],
    issuingAuthority: 'Empaneled Insurance Company (Agriculture Insurance Company, ICICI Lombard, etc.)',
    issuingOffice: 'Bank Branch / PMFBY Portal / CSC / Agriculture Office',
    validity: 'Valid for specific crop season only (Kharif or Rabi)',
    importantNotes: [
      'Apply before the cut-off date for the season — late applications are not accepted',
      'Declare the correct crop — mismatch causes claim rejection',
      'File crop loss claim within 72 hours of damage for timely settlement',
      'KCC holders should verify annual enrollment with their bank',
      'Crop area declared cannot exceed land area in official land records',
    ],
    commonMistakes: [
      'Missing the season cut-off date for enrollment',
      'Wrong crop declared in PMFBY policy vs actual crop grown',
      'Not filing crop loss intimation within 72 hours of damage',
    ],
    requiredInfo: ['Policy number', 'Farmer name', 'Crop insured', 'Land survey number', 'Sum insured', 'Premium paid', 'Insurance company name', 'Season'],
    relatedSchemes: ['PMFBY', 'RWBCIS', 'Kisan Credit Card', 'Agriculture Input Subsidy'],
    isMostRequired: false,
  },
  {
    id: 'irrigation_certificate',
    name: 'Water / Irrigation Certificate',
    category: 'agriculture',
    iconName: 'Droplets',
    tagline: 'Irrigation Source Registration — Water Resources Department',
    description: 'An Irrigation Certificate (Water Rights Certificate or Borewell Registration) certifies the type and availability of irrigation water source for a farmer\'s land — whether borewell, canal, tank, or other source.',
    whyRequired: 'PMKSY (Pradhan Mantri Krishi Sinchayee Yojana) and micro-irrigation subsidy schemes require proof of water source to qualify for drip irrigation, sprinkler systems, and water use efficiency improvement subsidies.',
    howToObtain: [
      'For borewells: Register with the Groundwater Department of the district',
      'For canal irrigation: Obtain water allocation certificate from Irrigation Department',
      'For tanks/ponds: Get membership certificate from Water User Association',
      'Apply at the District Water Resources Department office with land records',
    ],
    issuingAuthority: 'Water Resources Department / Groundwater Department',
    issuingOffice: 'District Water Resources Office / Irrigation Department / Water User Association',
    validity: '5 years (renewable)',
    importantNotes: [
      'Unregistered borewells disqualify farmers from drip/sprinkler irrigation subsidies',
      'Water User Association membership enables access to canal-based scheme benefits',
      'Water source must serve the specific survey number for which subsidy is applied',
      'Registration is also important for compliance with state groundwater regulation',
    ],
    commonMistakes: [
      'Using unregistered borewell — illegal borewells disqualify irrigation scheme benefits',
      'Water source mentioned doesn\'t match the land survey number in application',
      'Expired certificate not renewed before scheme application',
    ],
    requiredInfo: ['Farmer name', 'Survey number', 'Water source type', 'Department seal', 'Registration/Certificate number', 'Water allocation quantity if applicable'],
    relatedSchemes: ['PMKSY — Pradhan Mantri Krishi Sinchayee Yojana', 'Micro Irrigation Fund', 'Drip Irrigation Subsidy', 'Sprinkler Subsidy Scheme'],
    isMostRequired: false,
  },

  /* ────────────── OTHER ────────────── */
  {
    id: 'residence_certificate',
    name: 'Residence / Domicile Certificate',
    category: 'other',
    iconName: 'Home',
    tagline: 'Domicile Proof — Revenue Department / Tahsildar',
    description: 'A Residence Certificate (also called Domicile Certificate) certifies that a person has been residing in a particular state or district for a specified period. It is required for state-specific government scheme benefits and local reservations.',
    whyRequired: 'State government schemes such as Rythu Bharosa (Andhra Pradesh) require proof that the applicant is a legal resident of the state. It also helps qualify for state-specific agriculture subsidies and welfare programs.',
    howToObtain: [
      'Apply at Village Secretariat, MeeSeva, or Tahsildar\'s office',
      'Submit Aadhaar, ration card, and address proof documents',
      'Tahsildar verifies residence through official records or field inquiry',
      'Certificate issued within 7–10 working days',
    ],
    issuingAuthority: 'Revenue Department / Tahsildar',
    issuingOffice: 'Village Secretariat / MeeSeva / Mandal Revenue Office',
    validity: '3 years (renewable)',
    importantNotes: [
      'State and district must match the Aadhaar registered address',
      'Required when applying for schemes that have state-level farmer residency criteria',
      'Digital MeeSeva certificate is preferred over physical copy',
      'Update certificate if you change your residence district',
    ],
    commonMistakes: [
      'Expired certificate — 3-year validity',
      'Address doesn\'t match current Aadhaar address',
      'Wrong district mentioned on certificate vs scheme application',
    ],
    requiredInfo: ['Full name', 'Complete current address', 'State and district', 'Duration of residence', 'Tahsildar signature and seal'],
    relatedSchemes: ['Rythu Bharosa', 'PMFBY (State Component)', 'State Agriculture Subsidies', 'Local Government Welfare Schemes'],
    isMostRequired: false,
  },
  {
    id: 'mgnrega_job_card',
    name: 'MGNREGA Job Card',
    category: 'other',
    iconName: 'BriefcaseBusiness',
    tagline: 'Mahatma Gandhi NREGA — Gram Panchayat',
    description: 'The MGNREGA Job Card is an official document issued to rural households registered under the Mahatma Gandhi National Rural Employment Guarantee Act. It records employment guarantee entitlement, work done, and wages earned under the scheme.',
    whyRequired: 'MGNREGA-related agriculture convergence works (farm ponds, land leveling, horticulture pits, watershed development) require the job card. It also serves as rural income proof and residence documentation for other welfare applications.',
    howToObtain: [
      'Apply at the Gram Panchayat office with Aadhaar of all household members',
      'Household head submits application — all working-age members must be listed',
      'Job card issued within 15 days of application',
      'Digital job card available on MGNREGA MIS portal (nrega.nic.in)',
    ],
    issuingAuthority: 'Gram Panchayat / Block Development Office',
    issuingOffice: 'Gram Panchayat Office / Block Development Office',
    validity: 'Valid as long as the household remains rural and eligible',
    importantNotes: [
      'All working-age household members should be listed on the job card',
      'MGNREGA work is guaranteed — demand work at your Gram Panchayat if unemployed',
      'Wage payments are made via Aadhaar-linked bank accounts',
      'Job card is also proof of rural residence and income for other schemes',
    ],
    commonMistakes: [
      'Missing household member entries — reduces total wage entitlement days',
      'Illegible job card number',
      'Outdated Gram Panchayat — update when you change village/area',
    ],
    requiredInfo: ['Job card number', 'Household head name', 'Family member names', 'Gram Panchayat name', 'Work entries and wages'],
    relatedSchemes: ['MGNREGA', 'Farm Pond Scheme (MGNREGA convergence)', 'Watershed Management Works', 'Land Development under MGNREGA'],
    isMostRequired: false,
  },
];
